# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_14,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_14 ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then
          rev_base
        else
          "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "AFLplusplus-4.21.0-aA1y4dFrAAB5IR-iHNHVO3lwlK3Blq2Xx-9I3vsxOKMF";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "git+https://github.com/allyourcodebase/AFLplusplus#bf7d9cc91a3897c3ed9a65b04141c87dded1bfe7";
      hash = "sha256-INL603zLnfPYIGgUaOQ0DQBwsRQJ6L7kG61D8YosuzI=";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";
    path = fetchZigArtifact {
      name = "AFLplusplus";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-EffHfTfP9uf2WsfMVbq3kB4MYgjoRaOHZDlNBO1WezA=";
    };
  }
  {
    name = "zig_afl_kit-0.1.0-3k74fQAdAABrirJM84Lo-lnl9mnUMwtJCSPPyIJ0OzAr";
    path = fetchZigArtifact {
      name = "afl_kit";
      url = "git+https://github.com/kristoff-it/zig-afl-kit#676a439919c8ed736a84097f483d47d679f7e9df";
      hash = "sha256-wLHyZVjmUu6lNZBlGwuaX5XnKbEdMtov7YxJqn5IF3g=";
    };
  }
  {
    name = "N-V-__8AABhrAQAQLLLGadghhPsdxTgBk9N9aLVOjXW3ay0V";
    path = fetchZigArtifact {
      name = "diffz";
      url = "https://github.com/ziglibs/diffz/archive/ef45c00d655e5e40faf35afbbde81a1fa5ed7ffb.tar.gz";
      hash = "sha256-Hdj0Z4Fxv9JHaqdHQ+SLzhCq0rkMLfA406xrDvN/w7o=";
    };
  }
  {
    name = "N-V-__8AAAyYFwBMxWQCepH-NgMp6xo8gVqjRQ1lMPQnzYG9";
    path = fetchZigArtifact {
      name = "gfm";
      url = "git+https://github.com/kristoff-it/cmark-gfm#675efb13f41f1dcaebfa0e9dc42d9b504e4b5508";
      hash = "sha256-BUcc06/zCzz42/wVcT5z45hsfcMXNog3wOOvFiuUdio=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
    path = fetchZigArtifact {
      name = "known_folders";
      url = "git+https://github.com/ziglibs/known-folders#aa24df42183ad415d10bc0a33e6238c437fc0f59";
      hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
    };
  }
  {
    name = "lsp_codegen-0.1.0-CMjjo0ZXCQB-rAhPYrlfzzpU0u0u2MeGvUucZ-_g32eg";
    path = fetchZigArtifact {
      name = "lsp_codegen";
      url = "git+https://github.com/zigtools/zig-lsp-codegen#063a98c13a2293d8654086140813bdd1de6501bc";
      hash = "sha256-KzRi/a3FCS11Mryin9skkf3rFrIuoMP8+RcU0IuYNBA=";
    };
  }
  {
    name = "lsp_kit-0.1.0-hAAxO8C9AADemCOc0CmRChs50IY82liZno5pFFN8HJs5";
    path = fetchZigArtifact {
      name = "lsp_kit";
      url = "git+https://github.com/jcollie/zig-lsp-kit#5eddc1aa0296adfc3afa9f7600f146898945a9d8";
      hash = "sha256-6n3KPnxSPNfPxUyQ+9USKGWM8zr3K3CyxyQurvTPOtU=";
    };
  }
  {
    name = "scripty-0.1.0-LKK5O83DAADdUNWazHp_XAZFaByST5YlKJA3ZhoasRfH";
    path = fetchZigArtifact {
      name = "scripty";
      url = "git+https://github.com/jcollie/scripty#b6eae3983177a4797ae03b847a3c07ddbf0d7d11";
      hash = "sha256-yVgaN9ZUZ39593j2iLq0OFMsfplNUuHHJadF/TK0DUU=";
    };
  }
  {
    name = "superhtml-0.4.0-Y7MdPNiYDQAoUNtrz2_Rov6KLWBIt9kyQiX5jCvbD5OU";
    path = fetchZigArtifact {
      name = "superhtml";
      url = "git+https://github.com/jcollie/superhtml#4cf9693fb0b076e147cd5a2d75879beecbdf7c7a";
      hash = "sha256-ME+EawdXjnfLs7JmAsOZJWGHR1gf/Fy/pbbaApUmHfc=";
    };
  }
  {
    name = "tracy-0.0.0-4Xw-1pwwAABTfMgoDP1unCbZDZhJEfict7XCBGF6IdIn";
    path = fetchZigArtifact {
      name = "tracy";
      url = "git+https://github.com/kristoff-it/tracy#67d2d89e351048c76fc6d161e0ac09d8a831dc60";
      hash = "sha256-BKo1bhua/u+f5Z//ailur5aSHZWp3GiC0iwmVLrGZkE=";
    };
  }
  {
    name = "zig_yaml-0.1.0-C1161hVrAgDsyB2EZnq-Vp-QuZ9xJm2y0dECRXGG3UaP";
    path = fetchZigArtifact {
      name = "yaml";
      url = "git+https://github.com/kubkon/zig-yaml#27f63d3d2d13ed228d8fc077635205e6c2a405c7";
      hash = "sha256-aV2hIlcb5Y9h08H8JAWHy92YDK7rwT2PFBNwKsmSU0g=";
    };
  }
  {
    name = "ziggy-0.1.0-kTg8vwkbBgC28sEzl1CS-gPfbhK-oxDSOXRt8bx3r58D";
    path = fetchZigArtifact {
      name = "ziggy";
      url = "git+https://github.com/jcollie/ziggy#8cf802953b4454b1e944a293e6b85999280d4297";
      hash = "sha256-eL1aXey3yrDuU/NEfgtrhldny3QALQsTx4hPYT31QTM=";
    };
  }
]
